config/routes.rb
Rails.application.routes.draw do
  get 'relatorio/index'
  devise_for :users, 
  controllers: {
    registrations: 'user/registrations'
  }
  root 'home#index'
  post "home", to: "home#new"
  patch "home", to: "home#update"
  get "home", to: "home#teste"

  #patch "cobranca/:id", to: "cobranca#update" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/frequencia.rb
class Frequencia < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    begin
      @frequencia_atual = Frequencia.where(user_id:current_user.id, saida:nil).last
    rescue => exception
      @frequencia_atual = nil
    end
  end

  def new
    frequencia = Frequencia.new(user_id:current_user.id, entrada:Time.now, saida:nil)
    frequencia.save!
    redirect_to root_path
  end
  
  def update
    frequencia = Frequencia.where(user_id:current_user.id, saida:nil).last
    entrada = frequencia.entrada
    if Time.now > Time.new(entrada.year, entrada.month, entrada.day, entrada.hour + 1, entrada.min)
      if Time.new(entrada.year, entrada.month, entrada.day, 5).next_day > Time.now
        frequencia.update(saida: Time.now, fechou_o_ponto: true)
        redirect_to root_path
      else
        frequencia.update(saida: Time.now, fechou_o_ponto: false)
        redirect_to root_path
      end
    end
  end
end

app/controllers/relatorio_controller.rb
class RelatorioController < ApplicationController
  def index
    @frequencias = Frequencia.all.reverse
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, :configure_sign_up_params, only: [:update, :create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource({})
    resource
    yield resource if block_given?
    respond_with resource
  end

  # POST /resource/sign_up
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #  super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    sign_in_after_change_password? ? user_path(resource) : new_session_path(resource_name)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up) { |user| user.permit(permitted_attributes) }
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: permitted_attributes )
  end

  def permitted_attributes
    [
      :nome
    ]
  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:account_update)
  end
  
  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: permitted_attributes)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relatorio_helper.rb
module RelatorioHelper
end

app/views/home/index.html.erb
<div class="bg-white h-screen flex items-center justify-center">

  <!-- Card -->
  <card class="border-2 border-gray-300 rounded-2xl p-5 w-96">
  
    <!-- Caption -->
    <p class="text-2xl font-bold text-gray-700 text-center">Assinador de frequencia</p>

    <% unless @frequencia_atual.nil? %>
      <%= button_to("Eu ja vou!!", {:action =>"update"}, :method => :patch, :class=>"hover:bg-green-400 bg-green-500 delay-75 duration-100 text-white text-sm font-bold rounded-2xl w-full py-3 mt-7 border-b-4 border-b-green-600")%>
    <% else %>
      <%= button_to("Eu vim!!", {:action =>"new"}, :class=>"hover:bg-green-400 bg-green-500 delay-75 duration-100 text-white text-sm font-bold rounded-2xl w-full py-3 mt-7 border-b-4 border-b-green-600")%>
    <% end %>
  </card>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frequencia Reinabio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "collapse_navbar.js", :"data-turbo-track"=>"reload" %>
    <%= javascript_include_tag "collapse_menu_user.js", :"data-turbo-track"=>"reload" %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <%= yield %>
  </body>
</html>

app/views/relatorio/index.html.erb
<!-- component -->
<div class="flex flex-col h-screen">
    <div class="flex-grow overflow-auto">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-black-900 bg-gray-400">Nome</th>
            <th class="sticky top-0 px-6 py-3 text-black-900 bg-gray-400">Entrada</th>
            <th class="sticky top-0 px-6 py-3 text-black-900 bg-gray-400">Saida</th>
            <th class="sticky top-0 px-6 py-3 text-black-900 bg-gray-400">Fechou o ponto?</th>
          </tr>
        </thead>
        <tbody class="divide-y bg-gray-100">
        <% @frequencias.each do |frequencia| %>
        <%= turbo_frame_tag frequencia do %>
          <tr>
            <td class="px-6 py-4 text-center"><%= frequencia.user.nome %></td>
            <td class="px-6 py-4 text-center"><%= frequencia.entrada %></td>
            <td class="px-6 py-4 text-center"><%= frequencia.saida %></td>
            <td class="px-6 py-4 text-center"><%= frequencia.fechou_o_ponto %></td>
        <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->

<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <!-- menu mobi -->

      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">

        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu"  id='navbar-burger' onclick="hide_navbar();">
          <!--
            Icon when menu is closed.

            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!--
            Icon when menu is open.

            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <!-- menu desk -->

      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <%= link_to(image_tag("logo.png", :class=> "block lg:hidden h-12 w-auto"), root_path)%>
          <%= link_to(image_tag("logo.png", :class=> "hidden lg:block h-8 w-auto"), root_path)%>
        </div>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= render "shared/users_menu/botoes/inicio" %>
            <%= render "shared/users_menu/botoes/relatorio" %>
          </div>
        </div>
      </div>

      <!-- usuario -->

        <div class="buttons" id='signs'>
          <% if user_signed_in? %>
            <%= button_to("Sair", destroy_user_session_path, method: :delete, :class=>"focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900")%>
          <% else %>
            <%= link_to(image_tag("avatar.ico", :class=>"mx-auto h-12 w-auto"), new_user_session_path)%>
          <% end %>
        </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-4 space-y-1 hidden" id="nav-links">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <%= render "shared/users_menu/botoes_mobile/inicio" %>
      <%= render "shared/users_menu/botoes_mobile/relatorio" %>
    </div>
  </div>
</nav>

app/views/shared/users_menu/_menu.erb
<div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
  <button type="button" class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
    <span class="sr-only">View notifications</span>
    <!-- Heroicon name: outline/bell -->
    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
    </svg>
  </button>

  <!-- Profile dropdown -->
  <div class="ml-3 relative">
    <div>
      <button type="button" class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" onclick="hide_show(menu_user);">
        <span class="sr-only">Open user menu</span>
            <%= image_tag("avatar.ico", :class=>"h-12 w-12 rounded-full")%>
      </button>
    </div>

    <!--
      Dropdown menu, show/hide based on menu state.

      Entering: "transition ease-out duration-100"
        From: "transform opacity-0 scale-95"
        To: "transform opacity-100 scale-100"
      Leaving: "transition ease-in duration-75"
        From: "transform opacity-100 scale-100"
        To: "transform opacity-0 scale-95"
    -->
    <div class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" id="menu_user" aria-labelledby="user-menu-button" tabindex="-1">
      <!-- Active: "bg-gray-100", Not Active: "" -->
      <%= button_to("Sair", destroy_user_session_path, method: :delete, :class=>"block px-4 py-2 text-sm text-gray-700")%>
    </div>
  </div>
</div>

app/views/shared/users_menu/botoes/_inicio.erb
<% if (request.path.eql?(root_path)) %>
  <%= link_to("Inicio", root_path, :class=>"bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium",  :'aria-current' =>"page")%>
<% else %>
  <%= link_to("Inicio", root_path, :class=>"text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium")%>
<% end %>

app/views/shared/users_menu/botoes/_relatorio.erb
<% if (request.path.eql?(relatorio_index_path)) %>
<%= link_to("Relatório", relatorio_index_path, :class=>"bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium",  :'aria-current' =>"page")%>
<% else %>
<%= link_to("Relatório", relatorio_index_path, :class=>"text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium")%>
<% end %>

app/views/shared/users_menu/botoes_mobile/_inicio.erb
<% if (request.path.eql?(root_path)) %>
  <%= link_to("Inicio", root_path, :class=>"bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium",  :'aria-current' =>"page")%>
<% else %>
  <%= link_to("Inicio", root_path, :class=>"text-gray-300 hover:bg-gray-700 block hover:text-white px-3 py-2 rounded-md text-base font-medium")%>
<% end %>

app/views/shared/users_menu/botoes_mobile/_relatorio.erb
<% if (request.path.eql?(relatorio_index_path)) %>
<%= link_to("Relatório", relatorio_index_path, :class=>"bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium",  :'aria-current' =>"page")%>
<% else %>
<%= link_to("Relatório", relatorio_index_path, :class=>"text-gray-300 hover:bg-gray-700 block hover:text-white px-3 py-2 rounded-md text-base font-medium")%>
<% end %>

app/views/users/index.html.erb
<div class="bg-gray-100">
    <div class="container mx-auto my-5 p-5">
        <div class="md:flex no-wrap md:-mx-2 ">
            <!-- Left Side -->
            <div class="w-full md:w-3/12 md:mx-2">
                <!-- Profile Card -->
                <div class="bg-white p-3 border-t-4 border-green-400">
                    <% if @user.perfil.avatar.attached? %>
                      <div class="image overflow-hidden">
                        <%= image_tag(@user.perfil.avatar, :class=>"h-auto w-full mx-auto")%>
                      </div>
                    <% else %>
                        <%= image_tag("avatar.ico", :class=>"h-auto w-full mx-auto")%>
                    <% end %>
                    <h1 class="text-gray-900 font-bold text-xl leading-8 mt-10 mb-4"><%= @user.perfil.nome + " " + @user.perfil.sobrenome %></h1>
                    
                    <ul
                        class="bg-gray-100 text-gray-600 hover:text-gray-700 hover:shadow py-2 px-3 mt-3 divide-y rounded shadow-sm">
                        <% if @user.funcionario.eql?(1) %>
                        <li class="flex items-center py-3">
                            <span>Cargo</span>
                            <span class="ml-auto"><%= @user.funcionario.cargo %></span>
                        </li>
                        <% end %>
                        <li class="flex items-center py-3">
                            <span>Membro desde</span>
                            <span class="ml-auto"><%= (@user.created_at).to_s.split[0] %></span>
                        </li>
                    </ul>
                </div>
                <!-- End of profile card -->
                <div class="my-4"></div>
                
            </div>
            <!-- Right Side -->
            <div class="w-full md:w-9/12 mx-2 h-64">
                <!-- Profile tab -->
                <!-- About Section -->
                <div class="bg-white p-3 shadow-sm rounded-sm">
                    <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                        <span clas="text-green-500">
                            <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </span>
                        <span class="tracking-wide">Sobre</span>
                    </div>
                    <div class="text-gray-700">
                        <div class="grid md:grid-cols-2 text-sm">
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Nome</div>
                                <div class="px-4 py-2"><%= @user.perfil.nome %></div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Sobrenome</div>
                                <div class="px-4 py-2"><%= @user.perfil.sobrenome %></div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Genero</div>
                                <div class="px-4 py-2"><%= @user.perfil.sexo %></div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Contato</div>
                                <div class="px-4 py-2"><%= @user.perfil.telefone %></div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Endereço</div>
                                <div class="px-4 py-2"><%= @user.perfil.rua %> <%= @user.perfil.bairro %> <%= @user.perfil.cidade %> <%= @user.perfil.estado %></div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Complemento</div>
                                <div class="px-4 py-2"><%= @user.perfil.complemento %></div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Email</div>
                                <div class="px-4 py-2">
                                    <a class="text-blue-800" href="<%= @user.email %>"><%= @user.email %></a>
                                </div>
                            </div>
                            <div class="grid grid-cols-2">
                                <div class="px-4 py-2 font-semibold">Data de Nascimento</div>
                                <div class="px-4 py-2"><%= @user.perfil.nascimento %></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End of about section -->

                <div class="my-4"></div>

                <!-- Experience and education -->
                <div class="bg-white p-3 shadow-sm rounded-sm">

                    <div class="grid grid-cols-2">
                        <div>
                            <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8 mb-3">
                                <span clas="text-green-500">
                                    <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                    </svg>
                                </span>
                                <span class="tracking-wide">Experience</span>
                            </div>
                            <ul class="list-inside space-y-2">
                                <li>
                                    <div class="text-teal-600">Owner at Her Company Inc.</div>
                                    <div class="text-gray-500 text-xs">March 2020 - Now</div>
                                </li>
                                <li>
                                    <div class="text-teal-600">Owner at Her Company Inc.</div>
                                    <div class="text-gray-500 text-xs">March 2020 - Now</div>
                                </li>
                                <li>
                                    <div class="text-teal-600">Owner at Her Company Inc.</div>
                                    <div class="text-gray-500 text-xs">March 2020 - Now</div>
                                </li>
                                <li>
                                    <div class="text-teal-600">Owner at Her Company Inc.</div>
                                    <div class="text-gray-500 text-xs">March 2020 - Now</div>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8 mb-3">
                                <span clas="text-green-500">
                                    <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke="currentColor">
                                        <path fill="#fff" d="M12 14l9-5-9-5-9 5 9 5z" />
                                        <path fill="#fff"
                                            d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
                                    </svg>
                                </span>
                                <span class="tracking-wide">Education</span>
                            </div>
                            <ul class="list-inside space-y-2">
                                <li>
                                    <div class="text-teal-600">Masters Degree in Oxford</div>
                                    <div class="text-gray-500 text-xs">March 2020 - Now</div>
                                </li>
                                <li>
                                    <div class="text-teal-600">Bachelors Degreen in LPU</div>
                                    <div class="text-gray-500 text-xs">March 2020 - Now</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- End of Experience and education grid -->
                </div>
                <!-- End of profile tab -->
            </div>
        </div>
    </div>
</div>